name: 'cancel-currents-run'
description: 'Cancels Cypress or Playright runs via Currents API'
inputs:
  api-url:
    description: 'Currents API URL'
    required: false
    default: 'https://api.currents.dev/v1'
  api-token:
    description: 'Currents API token'
    required: true
  github-run-id:
    description: 'GitHub run id'
    required: true
  github-run-attempt:
    description: 'GitHub run attempt'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
